version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: ./kafka-docker
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "items:8:1,invalid_items:8:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongodb:
    image: tozd/mongodb:3.4
    volumes:
      - ./data/mongodb:/var/lib/mongodb
    ports:
      - '27017:27017'

  bidder-api:
    container_name: bidder-api
    build: ./bidder
    command: uvicorn app.app_main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8001:8000
    environment:
      MONGODB_DSN: "mongodb://mongodb:27017"
      KAFKA_HOST: "kafka:9092"
      EVENTS_TOPIC: items
      USERS_COLLECTION: "users"
      ITEMS_COLLECTION: "items"
      EVENTS_COLLECTION: "events"
      MONGODB_STORAGE: "bidder"

  bidder-streamer:
    container_name: bidder-streamer
    build: ./bidder
    depends_on:
      - "kafka"
    command: bash wait_for_service.sh
    environment:
      MONGODB_DSN: "mongodb://mongodb:27017"
      KAFKA_HOST: "kafka:9092"
      EVENTS_TOPIC: "items"
      USERS_COLLECTION: "users"
      ITEMS_COLLECTION: "items"
      EVENTS_COLLECTION: "events"
      MONGODB_STORAGE: "bidder"
      EVENTS_INVALID_TOPIC: "invalid_items"
